############################
## CHANGE THESE
############################

baseURL: 'https://devanshimirchandani.github.io/qubt'
title: 'Devanshi Mirchandani'

############################
############################

enableEmoji: true
disableKinds: ['taxonomy', 'term']
languageCode: 'en-au'
enableRobotsTXT: true

markup:
  _merge: deep
