############################
## Navbar
############################

main:
- name: Home
  url: /
  weight: 10
# - name: Blog
#   url: /blog/
#   weight: 20
- name: About
  url: /about/
  weight: 30
- name: Resume
  url: /resume/
  weight: 30