############################
## Author
############################

author:
  name: "Devanshi Mirchandani"
  image: author.png
  greeting: "Building. Breaking. Learning."
  # icon: ":wave:"

about:
  name: "Devanshi Mirchandani"
  image: about.png
  # icon: ":wave:"

############################
## Links
############################

links:
  - github: https://github.com/devanshimirchandani
  # - facebook: 
  # - x-twitter:
  # - mastodon:
  - linkedin: https://www.linkedin.com/in/devanshi-mirchandani/
  # - instagram:
  # - reddit: 
  # - telegram: 
  # - whatsapp: 
  # - signal: 
  # - codepen: 
  # - dev: 
  - email: mailto:devanshi.mirchandani@gmail.com
  # - website:
  # - link: 
  # - discord:
  # - orcid:
  # - slack:
  # - stack-overflow: 
  # - twitch: 
  # - patreon: 
  # - soundcloud:
  # - dribbble: 
  # - stack-exchange: 
  # - tiktok: 
  # - youtube:
  # - keybase: 
  # - flickr: 
  # - tumblr:
  # - kickstarter: 
  # - snapchat:
  # - bluesky: 
  # - bitbucket:
  # - bandcamp: 
  # - etsy: 
  # - spotify: 
  # - pinterest: 
  # - strava: 
  # - untappd: 
  # - skype: 
  # - medium: 
  # - foursquare: 
  # - apple: 
  # - amazon: 
  # - google: 
  # - paypal: 
  # - windows: 

###############################
## OpenGraph & Twitter Cards
###############################

title: "Devanshi Mirchandani"
description: "Portfolio Website"
images:
  - logo.png